### ISSUE TITLE
Add sip to the default ignore list

### ISSUE THREAD

**Issue by anntzer** [bwesterb/py-demandimport#6]
sip is a wrapper generator for c/c++ libraries, used e.g. by PyQt (https://www.riverbankcomputing.com/software/sip/intro).  Demand-importing sip causes PyQt to crash at import time
```
$ python -c 'import demandimport; demandimport.enable(); from PyQt5 import QtCore'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
SystemError: initialization of QtCore failed without raising an exception
```
but ignoring sip solves the issue.

**Comment by bwesterb** [comment]
It's in 0.3.4.  Can you check if it works now?

**Comment by anntzer** [comment]
It does, but demandimporting complex modules still fails sometimes.  For example, demandimporting matplotlib.pyplot fails when importing numpy.core.multiarray, and even if we pre-import numpy, that later fails with the curious
```
AttributeError: module 'matplotlib' has no attribute 'collections'
```
It is a bit curious that the last line of the traceback is *not* a call to `_origimport`.

However, I wonder whether a more robust strategy is possible (well I have no proof that it is more robust, just some guess).
Do not use a proxy object to represent demandimported modules.  Instead, whenever `__import__` is called, just register the import statement somewhere without executing it, and swap the *current* module's class with a subclass of ModuleType, which defines `__getattr__` (or overrides `__dict__`, perhaps) so that unresolved attributes are matched against the import list.  (See e.g. https://github.com/njsmith/metamodule for module class swapping.)

**Comment by bwesterb** [comment]
I don't have enough information to reproduce your problem with `numpy.core.multiarray`.  Could you write an explicit test-case for it?

I'm happy to replace the internals of demandimport with something better (i.e. it doesn't break existing projects).  I don't have time for it myself, but I'm happy to support you.

**Comment by anntzer** [comment]
```
$ python -c 'import demandimport as d; d.enable(); import matplotlib.pyplot as plt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 116, in __getattribute__
    self._load()
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 81, in _load
    mod = _origimport(path, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/__init__.py", line 122, in <module>
    from matplotlib.cbook import is_string_like, mplDeprecation, dedent, get_label
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/cbook.py", line 33, in <module>
    import numpy.ma as ma
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 116, in __getattribute__
    self._load()
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 81, in _load
    mod = _origimport(path, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 130, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 116, in __getattribute__
    self._load()
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 79, in _load
    mod = _origimport(path, globals, locals, fromlist)
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
SystemError: initialization of multiarray raised unreported exception
```

That may be related to the fact that we're dealing with an extension package, so let's preload numpy and stick to pure python:
```
$ python -c 'import numpy; import demandimport as d; d.enable(); from matplotlib import pyplot as plt; plt.show()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/pyplot.py", line 37, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 40, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 130, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/usr/lib/python3.6/site-packages/demandimport/__init__.py", line 164, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 21, in <module>
    import matplotlib.collections as mcoll
AttributeError: module 'matplotlib' has no attribute 'collections'
```

**Comment by bwesterb** [comment]
```python
demandimport.ignore('collections.abc')                                           
demandimport.ignore('matplotlib.collections')                                    
demandimport.ignore('matplotlib.contour')
```

fixes it.

**Comment by anntzer** [comment]
Thank you.
Still, it would be nice to understand why this is necessary...
