### ISSUE TITLE
Suggest adding collections.abc to the ignore list

### ISSUE THREAD

**Issue by skrap** [bwesterb/py-demandimport#8]
The `typing` module uses conditional importing of `collections.abc`, which is breaking under demandimport.

To reproduce:
* python 2.7.14
* typing-3.5.2.2 (but probably several others)
```
import demandimport
demandimport.enable()
import typing
typing.Any
```

Result:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    typing.Any
  File "/usr/lib/python2.7/site-packages/demandimport/__init__.py", line 117, in __getattribute__
    self._load()
  File "/usr/lib/python2.7/site-packages/demandimport/__init__.py", line 80, in _load
    mod = _origimport(path, globals, locals, fromlist)
  File "usr/lib/python2.7/site-packages/typing.py", line 1321, in <module>
  File "/usr/lib/python2.7/site-packages/demandimport/__init__.py", line 117, in __getattribute__
    self._load()
  File "/usr/lib/python2.7/site-packages/demandimport/__init__.py", line 80, in _load
    mod = _origimport(path, globals, locals, fromlist)
ImportError: No module named abc
```

Suggested change:
Add `collections.abc` to the default ignore list.  That resolves the issue.

For reference, here's the misbehaving code, right at the top of this file:
https://github.com/python/cpython/blob/3.6/Lib/typing.py

**Comment by bwesterb** [comment]
Thanks.  (`typing` isn't a python2 module, btw)
